@extends('frontend.layouts.app')

@section('content')
    <section class="bg0 p-b-70 p-t-5">
        <!-- Title -->
            <div class="container h-full flex-col-e-c p-b-58">
                <h3 class="f1-l-5 cl0 p-b-16 txt-left respon2" style="color: #0a0a0a">
                    Privacy Policy
                </h3>

                <div class="flex-wr-c-s">
					<span class="f1-s-3 cl8 m-rl-7 txt-left">
						<a href="#" class="f1-s-4 cl8 hov-cl10 trans-03">
							by Talamedia.id
						</a>
						<span class="m-rl-3">-</span>
					</span>
                </div>
            </div>

        <!-- Detail -->
        <div class="container p-t-82">
            <div class="row justify-content-center">
                <div class="col-md-10 col-lg-8 p-b-100">
                    <div class="p-r-10 p-r-0-sr991">
                        <!-- Blog Detail -->
                        <div class="p-b-70">
                            <div class="">
                                <p>This website uses Google Analytics, a web analytics service provided by Google, Inc. ("Google"). Google Analytics uses "cookies", which are text files saved on your computer, to help the website analyze how you use the site. The information generated by the cookie about your use of the website will be transmitted to and stored by Google on servers in the United States.&nbsp;</p>
                                <p><br>
                                </p>
                                <p>If this website anonymizes IP addresses, your IP address will be truncated by Google within a EU member state or other EEA state before being transmitted to the US. Only in exceptional situations will your full IP address be transmitted to Google servers in the United States and truncated there. Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity for website operators and providing other services relating to website activity and internet usage. Google will not associate your IP address with any other data held by Google.
                                </p><p><br></p><p>You may refuse the use of cookies by selecting the appropriate settings on your browser, however please note that if you do this you may not be able to use the full functionality of this website. By using this website, you consent to the processing of data about you by Google in the manner and for the purposes set out above. You can also prevent Google from collecting information (including your IP address) via cookies and processing this information by downloading this browser plugin and installing it: <a href="https://tools.google.com/dlpage/gaoptout">https://tools.google.com/dlpage/gaoptout
                                    </a></p><p><br></p><p>You can prevent data collection via Google Analytics by adjusting your <a href="/cookie-settings/">Cookie Settings</a>.</p><p><br></p><p>Further information concerning the terms and conditions of use and data privacy can be found at the <a href="https://www.google.com/analytics/terms/us.html">Google Analytics Terms of Service</a> or at the <a href="https://www.google.com/analytics/learn/privacy.html">Google Analytics Privacy Overview</a>. Please note that on this website, Google Analytics is supplemented by "gat._anonymizeIp();" to ensure anonymized collection of IP addresses (IP masking).
                                </p></div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection
